# Generated by Django 3.2.9 on 2022-01-21 07:09

from django.db import migrations, models
import formula1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_serial', models.CharField(max_length=50)),
                ('circuit_name', models.CharField(max_length=30)),
                ('circuit_location', models.CharField(max_length=30)),
                ('circuit_length', models.CharField(max_length=3)),
                ('circuit_description', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'circuit',
            },
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=50)),
                ('total_points', models.CharField(max_length=5)),
                ('team_team_id', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=formula1.models.filepath)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=5)),
                ('quantity', models.CharField(max_length=10)),
                ('team_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'merch',
            },
        ),
        migrations.CreateModel(
            name='participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('schedule_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'participation',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=50)),
                ('schedule_name', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=100)),
                ('schedule_date', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('circuit_serial', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
                ('avg_speeds', models.CharField(max_length=30)),
                ('laps', models.CharField(max_length=5)),
                ('points', models.CharField(max_length=5)),
                ('driver_id', models.CharField(max_length=50)),
                ('schedule_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'standings',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=20)),
                ('base', models.CharField(max_length=20)),
                ('pole_position', models.CharField(max_length=20)),
                ('world_championship', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=5)),
                ('schedule_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
